# Generated by Django 5.1.1 on 2024-12-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
